name: AcheSoldin
version: 1.0.0
main: ru.achesoldin.AcheSoldinPlugin
api-version: 1.16
commands:
  scheck:
    description: Start a cheat check on a player
    usage: /scheck <player>
  sds:
    description: Provide Discord during check
    usage: /sds <discord>
  scban:
    description: Ban a player after check
    usage: /scban <player>
  screlease:
    description: Release a player from check
    usage: /screlease <player>
